### ISSUE TITLE
Unexpected token --> aws-sso-cli/lib/web.js:32

### ISSUE THREAD

**Issue by anders-rapp-wcar** [codeeno/aws-sso-cli#2]
(node:9086) ExperimentalWarning: The ESM module loader is experimental.
(node:9086) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
file:///home/aa100027/.nvm/versions/node/v13.7.0/lib/node_modules/aws-sso-cli/lib/web.js:32
      SigninToken: encodeURI(response?.data?.SigninToken),
                                      ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:66:18)

**Comment by codeeno** [comment]
Hi,

That piece of code uses the [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operator, which is why the app needs at least Node 14 to run.
