### ISSUE TITLE
Pattern Match on profile URL of SSO

### ISSUE THREAD

**Issue by nbaillie** [codeeno/aws-sso-cli#3]
Pattern match for sso profiles in profiles.js with a '-' in them to not pass the regex.

for example:
/^https?:\/\/\w+\.awsapps.com\/start$/g

will not match:
https://my-sso.awsapps.com/start

This prevents creating profiles with this and perhaps other chars.

**Comment by codeeno** [comment]
Hi there,

Thanks a lot for bringing this up!

I just pushed [a fix](https://github.com/codeeno/aws-sso-cli/commit/a85fb1ff7bba93c7a3155582c0210ac8121dc182) to allow hyphens. I'm not sure if there are other chars that SSO allows (can't find any documentation about it right now) but if the [https://docs.aws.amazon.com/IAM/latest/UserGuide/console_account-alias.html](IAM account aliases) are anything to go by it should only be letters, digits and hyphens.

Cheers!
