### ISSUE TITLE
automatically option chose when there's only one option 

### ISSUE THREAD

**Issue by roeera** [codeeno/aws-sso-cli#6]
Hi,

I would examine an option to automatically chose and option when there's only one option.
e.g. :
```
aws-sso-cli                                                                                                              
? Select the SSO profile. (Use arrow keys)
❯ main
```

in such case, move on with main... (no need to push "enter")
also for account role choosing:

```
? Select the account role you wish to assume: (Use arrow keys or type to search)
❯ AdministratorAccess
```

wdyt ?

Tx

**Comment by codeeno** [comment]
Good Idea! That will speed it up a little especially since you'll often only have 1 role to choose from anyways.

[I added it](https://github.com/codeeno/aws-sso-cli/commit/0b60eaf273b358525d3c9e4613fd8d30813fc23b) real quick and made a new release.
